name: 👾 Bug
description: File a bug/issue
title: "[BUG] "
labels: ["Bug"]
projects: ["Active Framework"]

body:
- type: textarea
  id: contexte
  attributes:
    label: 💡 Description
    placeholder: Description of a new feature
    value:
  validations:
    required: true
- type: textarea
  id: reproductionStages
  attributes:
    label: 🔎 Reproduction Stages
    placeholder: Please, describe all reproduction stages
    value:
  validations:
    required: false
- type: textarea
  id: workToDo
  attributes:
    label: 🔧 Work To Do
    placeholder: What needs to be done
    value:
  validations:
    required: true
- type: input
  id: stationLink
  attributes:
    label: ℹ Station Link
    placeholder: Teams Hyperlink
  validations:
    required: false
- type: input
  id: stationCredentials
  attributes:
    label: ℹ Station Credentials
    placeholder: admin / Niagara123
  validations:
    required: false
- type: input
  id: componentOrd
  attributes:
    label: ℹ Component Ord
    placeholder: station:|slot:/Drivers/...
  validations:
    required: false
- type: textarea
  id: stackTrace
  attributes:
    label: ℹ Stack Trace
    placeholder: java.lang.NullPointerException ...
  validations:
    required: false
- type: textarea
  id: test
  attributes:
    label: 💻 Test description
    value:
  validations:
    required: false