name: 💡 Feature Request
description: Description of a new feature
title: "[Component] "
labels: ["FeatureRequest"]
projects: ["Active Framework"]

body:
- type: textarea
  id: contexte
  attributes:
    label: Description
    placeholder: Description of a new feature
    value: 
  validations:
    required: true
- type: textarea
  id: useCase
  attributes:
    label: Use Case
    placeholder: Please, describe one or more use cases
    value: 
  validations:
    required: false
- type: textarea
  id: workToDo
  attributes:
    label: Work To Do 
    placeholder: What needs to be done
    value: 
  validations:
    required: true
- type: textarea
  id: test
  attributes:
    label: Test description
    value: 
  validations:
    required: false